microservice/everest/src/main/java/org/javaee7/wildfly/samples/everest/catalog/CatalogBean.java
package org.javaee7.wildfly.samples.everest.catalog;

import java.io.Serializable;
import java.io.StringReader;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.json.Json;
import javax.json.JsonObject;
import javax.ws.rs.client.Entity;
import javax.ws.rs.core.Response;
import org.javaee7.wildfly.samples.services.discovery.ServiceDiscovery;

/**
 * @author arungupta
 */
@Named
@SessionScoped
public class CatalogBean implements Serializable {
    @Inject CatalogItem catalogItem;
    
    @Inject ServiceDiscovery services;

    String status;
    
    public void addCatalog() {
        Response response = services.getCatalogService().request().post(Entity.xml(catalogItem));

        Response.StatusType statusInfo = response.getStatusInfo();
        
        if (statusInfo.getStatusCode() == Response.Status.CREATED.getStatusCode())
            status = "User added successfully";
        else
            status = statusInfo.getReasonPhrase();
    }
    
    public CatalogItem[] getAllItems() {
        return services.getCatalogService().register(CatalogItem.class).request().get(CatalogItem[].class);
    }

    public String catalogServiceEndpoint() {
        String itemId = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("itemId");

        String response = services.getCatalogService().path(itemId).request().get(String.class);
        
        JsonObject jsonObject = Json.createReader(new StringReader(response)).readObject();
        catalogItem.setId(jsonObject.getInt("id"));
        catalogItem.setName(jsonObject.getString("name"));
        catalogItem.setDescription(jsonObject.getString("description"));
        
        return response;
    }
    
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}

microservice/everest/src/main/java/org/javaee7/wildfly/samples/everest/checkout/OrderBean.java
package org.javaee7.wildfly.samples.everest.checkout;

import java.io.Serializable;
import java.io.StringReader;
import java.io.StringWriter;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.json.Json;
import javax.json.JsonArray;
import javax.json.JsonObject;
import javax.json.JsonWriter;
import javax.ws.rs.client.Entity;
import javax.ws.rs.core.Response;
import org.javaee7.wildfly.samples.everest.cart.Cart;
import org.javaee7.wildfly.samples.everest.cart.CartItem;
import org.javaee7.wildfly.samples.services.discovery.ServiceDiscovery;

/**
 * @author arungupta
 */
@Named
@SessionScoped
public class OrderBean implements Serializable {

    @Inject
    Order order;

    @Inject
    Cart cart;

    String status;

    @Inject ServiceDiscovery services;

    public void saveOrder() {
        List<CartItem> cartItems = cart.getItems();
        cartItems.stream().map((cartItem) -> {
            OrderItem orderItem = new OrderItem();
            orderItem.itemId = cartItem.getItemId();
            orderItem.itemCount = cartItem.getItemCount();
            return orderItem;
        }).forEach((orderItem) -> {
            order.getOrderItems().add(orderItem);
        });

        try {
            JsonArray orderItems = null;
            for (OrderItem orderItem : order.getOrderItems()) {
                orderItems = Json.createArrayBuilder()
                        .add(Json.createObjectBuilder()
                                .add("itemId", orderItem.getItemId())
                                .add("itemCount", orderItem.getItemCount()))
                        .build();
            }
            JsonObject jsonObject = Json.createObjectBuilder()
                    //                    .add("orderId", order.getOrderId())
                    .add("orderItems", orderItems)
                    .build();
            StringWriter writer = new StringWriter();
            try (JsonWriter w = Json.createWriter(writer)) {
                w.write(jsonObject);
            }

            Response response = services.getOrderService().request().post(Entity.json(writer.toString()));

            Response.StatusType statusInfo = response.getStatusInfo();

            if (statusInfo.getFamily() == Response.Status.Family.SUCCESSFUL) {
                JsonObject jsonResponse = Json.createReader(new StringReader(response.readEntity(String.class))).readObject();
                status = "Order successful, order number: " + jsonResponse.get("orderId");;
            } else {
                status = statusInfo.getReasonPhrase();
            }

            cart.clearCart();
        } catch (Exception e) {
            status = e.getLocalizedMessage();
        }
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}

microservice/everest/src/main/java/org/javaee7/wildfly/samples/everest/uzer/UzerBean.java
package org.javaee7.wildfly.samples.everest.uzer;

import java.io.Serializable;
import java.io.StringReader;
import java.io.StringWriter;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.json.Json;
import javax.json.JsonObject;
import javax.json.JsonWriter;
import javax.ws.rs.client.Entity;
import javax.ws.rs.core.Response;
import org.javaee7.wildfly.samples.services.discovery.ServiceDiscovery;

/**
 * @author arungupta
 */
@Named
@SessionScoped
public class UzerBean implements Serializable {
    @Inject UzerItem uzerItem;
    
    @Inject ServiceDiscovery services;
    
    String status;
    
    public void addUzer() {
        
        JsonObject jsonObject = Json.createObjectBuilder()
                .add("login", uzerItem.getLogin())
                .add("password", uzerItem.getPassword())
                .add("username", uzerItem.getUsername())
                .add("address1", uzerItem.getAddress1())
                .add("address2", uzerItem.getAddress2())
                .add("city", uzerItem.getCity())
                .add("state", uzerItem.getState())
                .add("country", uzerItem.getCountry())
                .add("zip", uzerItem.getZip())
                .add("creditcard", uzerItem.getCreditcard())
                .build();
        StringWriter w = new StringWriter();
        try (JsonWriter writer = Json.createWriter(w)) {
            writer.write(jsonObject);
        }
        
        Response response = services.getUserService().request().post(Entity.xml(w.toString()));

        Response.StatusType statusInfo = response.getStatusInfo();
        
        if (statusInfo.getFamily() == Response.Status.Family.SUCCESSFUL) {
            JsonObject jsonResponse = Json.createReader(new StringReader(response.readEntity(String.class))).readObject();
            status = "User added successfully," +
                    " login: " + jsonResponse.get("login") +
                    " password: " + jsonResponse.get("password");
        } else
            status = statusInfo.getReasonPhrase();
    }
    
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}

microservice/everest/src/main/webapp/cart.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>
        <f:view contracts="main">

            <ui:composition template="/template.xhtml">

                <ui:define name="content">
                    <h2>Cart</h2>
                    <h:dataTable value="#{cart.items}" var="item" border="1">
                        <h:column>
                            <f:facet name="header">Item Name</f:facet>
                                #{item.itemName}
                        </h:column>

                        <h:column>
                            <f:facet name="header">Item Count</f:facet>
                                #{item.itemCount}
                        </h:column>
                    </h:dataTable>
                    <p/>
                    <h:form>
                        <h:commandButton value="Continue Shopping" action="catalog"/>
                        <h:commandButton value="Checkout" action="checkout"/>
                    </h:form>
                </ui:define>

            </ui:composition>

        </f:view>

    </body>
</html>

microservice/everest/src/main/webapp/catalog-item.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <f:view contracts="main">
            <ui:composition template="/template.xhtml">

                <ui:define name="content">
                    <h2>Catalog Item</h2>

                    <h:form>
                        <b>Name:</b> #{catalogItem.name}<p/>
                        <b>Description:</b> #{catalogItem.description}<p/>
                        <b>Quantity:</b> 
                        <h:selectOneMenu id="itemCount"
                                         value="#{cartItem.itemCount}">
                            <f:selectItem id="item1" itemLabel="1" itemValue="1" />
                            <f:selectItem id="item2" itemLabel="2" itemValue="2" />
                            <f:selectItem id="item3" itemLabel="3" itemValue="3" />
                            <f:selectItem id="item4" itemLabel="4" itemValue="4" />
                            <f:selectItem id="item5" itemLabel="5" itemValue="5" />
                        </h:selectOneMenu><p/>
                        <p/>
                        <h:commandButton value="Add to Cart" action="cart" actionListener="#{cart.addItemToCart}">
                            <f:param name="itemId" value="#{catalogItem.id}"/>
                            <f:param name="itemName" value="#{catalogItem.name}"/>
                        </h:commandButton>
                    </h:form>
                </ui:define>
            </ui:composition>

        </f:view>
    </body>
</html>

microservice/everest/src/main/webapp/catalog.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <f:view contracts="main">
            <ui:composition template="/template.xhtml">

                <ui:define name="content">
                    <h2>Catalog</h2>

                    <h:dataTable value="#{catalogBean.allItems}" var="item">
                        <h:column>
                            <f:facet name="header">Item Name</f:facet>
                            <h:form>
                                <h:commandLink value="#{item.name}" action="catalog-item" actionListener="#{catalogBean.catalogServiceEndpoint()}">
                                    <f:param name="itemId" value="#{item.id}"/>
                                </h:commandLink>
                            </h:form>
                        </h:column>

                        <h:column>
                            <f:facet name="header">Item Type</f:facet>
                                #{item.type}
                        </h:column>

                        <h:column>
                            <f:facet name="header">Item Description</f:facet>
                                #{item.description}
                        </h:column>
                    </h:dataTable>

                </ui:define>

            </ui:composition>

        </f:view>

    </body>
</html>

microservice/everest/src/main/webapp/checkout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <f:view contracts="main">

            <ui:composition template="/template.xhtml">

                <ui:define name="content">
                    <h2>Shipping</h2>
                    <h:form>
                        Login name: <h:inputText value="#{uzerItem.login}"/> <p/>

                        <h:commandButton value="Show Details" action="checkout" actionListener="#{shipping.findShippingDetail()}"/>
                        <p/>

                        <b>Name:</b> #{uzerItem.username} <p/>
                        <b>Address Line 1:</b> #{uzerItem.address1} <p/>
                        <b>Address Line 2:</b> #{uzerItem.address2} <p/>
                        <b>City:</b> #{uzerItem.city} <p/>
                        <b>State:</b> #{uzerItem.state} <p/>
                        <b>Zip:</b> #{uzerItem.zip} <p/>
                        <b>Country:</b> #{uzerItem.country} <p/>
                        <b>Credit Card:</b> #{uzerItem.creditcard} <p/>

                        <h:commandButton value="Confirm and Pay" action="confirm" actionListener="#{orderBean.saveOrder()}"/>
                    </h:form>

                </ui:define>

            </ui:composition>

        </f:view>
    </body>
</html>

microservice/everest/src/main/webapp/confirm.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <f:view contracts="main">
            <ui:composition template="/template.xhtml">

                <ui:define name="content">
                    <h2>Order Confirmation</h2>

                    #{orderBean.status}

                    <p/>

                    <h:form>
                        <h:commandButton value="Continue Shopping?" action="catalog"/>
                    </h:form>
                </ui:define>
            </ui:composition>

        </f:view>
    </body>
</html>

microservice/everest/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <f:view contracts="main">
            <ui:composition template="/template.xhtml">

                <ui:define name="content">
                    <ul>
                        <li>Create User</li>
                        <li>Add items from Catalog to Shopping Cart</li>
                        <li>Review Shopping Cart</li>
                        <li>Confirm/Add Shipping Address</li>
                        <li>Add Payment Details</li>
                    </ul>

                    <h:form>
                        <h:commandButton value="Create User" action="user"/>
                    </h:form>
                </ui:define>

            </ui:composition>
        </f:view>

    </body>
</html>

microservice/everest/src/main/webapp/user-status.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <f:view contracts="main">
            <ui:composition template="/template.xhtml">

                <ui:define name="content">
                    <h2>Create User Status</h2>

                    #{uzerBean.status}
                    <p/>

                    <h:form>
                        <h:commandButton value="Start Shopping" action="catalog"/>
                    </h:form>
                </ui:define>
            </ui:composition>
        </f:view>

    </body>
</html>

microservice/everest/src/main/webapp/user.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <f:view contracts="main">
            <ui:composition template="/template.xhtml">

                <ui:define name="content">
                    <h2>Create User</h2>

                    <h:form>
                        <b>Login:</b> <h:inputText value="#{uzerItem.login}"/> <p/>
                        <b>Password:</b> <h:inputSecret value="#{uzerItem.password}" /> <p/>
                        <b>Name:</b> <h:inputText value="#{uzerItem.username}"/> <p/>
                        <b>Address Line 1:</b> <h:inputText value="#{uzerItem.address1}"/> <p/>
                        <b>Address Line 2:</b> <h:inputText value="#{uzerItem.address2}"/> <p/>
                        <b>City:</b> <h:inputText value="#{uzerItem.city}"/> <p/>
                        <b>State:</b> <h:inputText value="#{uzerItem.state}"/> <p/>
                        <b>Zip:</b> <h:inputText value="#{uzerItem.zip}"/> <p/>
                        <b>Country:</b> <h:inputText value="#{uzerItem.country}"/> <p/>
                        <b>Credit Card:</b> <h:inputText value="#{uzerItem.creditcard}"/> <p/>

                        <p/>
                        <h:commandButton value="Create User" action="user-status" actionListener="#{uzerBean.addUzer()}"/>
                    </h:form>
                </ui:define>
            </ui:composition>
        </f:view>

    </body>
</html>